### ISSUE TITLE
Migrate to System.Reactive

### ISSUE THREAD

**Issue by isaacmcn** [neuecc/EtwStream#15]
Hi,

Have been playing around with EtwStream and it is looking really good. Much easier to use than some other alternatives. It would be good to migrate from Rx-Main to the System.Reactive.\* nuget packages if possible.

Cheers,

Isaac

**Comment by neuecc** [comment]
Thank you.

Yes, I should do it!

**Comment by neuecc** [comment]
I've uploaded 1.3.3!
